version: '3.2'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    tty: true
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=blogPHP
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
    volumes:
      - ./mariadb/data:/var/lib/mysql
